services:
  - type: web
    name: campaign-manager-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: http://18.206.140.165:5001/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 